"""
Search / RAG microservice
=========================
Pipeline:  text  --(embed via Ollama)-->  768-dim vector  --(store/query)-->  Milvus

Endpoints (namespaced under /search so the path is the same direct or via Nginx):
  POST /search/index   {text, source?}        -> embeds + stores a document
  POST /search/query   {query, top_k?}        -> semantic search, returns nearest docs
  GET  /search/health                         -> checks Milvus + Ollama connectivity
  GET  /metrics                               -> Prometheus scrape endpoint

Why these choices:
- Embeddings are generated by the existing Ollama container (nomic-embed-text),
  so the search service stays light: no PyTorch / sentence-transformers inside.
- Collection + index are created lazily on startup if they don't exist, so a
  fresh `docker compose up` just works.
"""

import time
import logging
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.responses import PlainTextResponse, JSONResponse
from pydantic import BaseModel, Field
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from pymilvus import (
    connections,
    utility,
    Collection,
    CollectionSchema,
    FieldSchema,
    DataType,
)

from .config import settings

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("search-service")

# --- Prometheus metrics --------------------------------------------------------
REQUESTS = Counter("search_requests_total", "Total requests", ["endpoint", "status"])
LATENCY = Histogram("search_request_duration_seconds", "Latency (s)", ["endpoint"])
EMBED_LATENCY = Histogram("search_embed_duration_seconds", "Embedding call latency (s)")


# --- Request/response models ---------------------------------------------------
class IndexRequest(BaseModel):
    text: str = Field(..., min_length=1)
    source: str = "manual"


class QueryRequest(BaseModel):
    query: str = Field(..., min_length=1)
    top_k: int | None = None


# --- Milvus collection bootstrap ----------------------------------------------
def connect_with_retry(retries: int = 30, delay: float = 2.0):
    """Milvus can take a while to become ready; retry the initial connection."""
    last_err = None
    for attempt in range(1, retries + 1):
        try:
            connections.connect(
                alias="default",
                host=settings.milvus_host,
                port=settings.milvus_port,
            )
            log.info("Connected to Milvus at %s:%s", settings.milvus_host, settings.milvus_port)
            return
        except Exception as e:  # noqa: BLE001
            last_err = e
            log.warning("Milvus not ready (attempt %d/%d): %s", attempt, retries, e)
            time.sleep(delay)
    raise RuntimeError(f"Could not connect to Milvus: {last_err}")


def ensure_collection() -> Collection:
    """Create the collection + vector index on first run, otherwise reuse it."""
    name = settings.collection_name
    if not utility.has_collection(name):
        log.info("Creating collection '%s'", name)
        fields = [
            # auto_id=True -> Milvus assigns the primary key for us.
            FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
            FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=65535),
            FieldSchema(name="source", dtype=DataType.VARCHAR, max_length=512),
            FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=settings.embed_dim),
        ]
        schema = CollectionSchema(fields, description="Documents for semantic search")
        coll = Collection(name=name, schema=schema)
        # HNSW = fast approximate nearest-neighbour index. COSINE matches how
        # text embeddings are usually compared (direction, not magnitude).
        coll.create_index(
            field_name="vector",
            index_params={
                "index_type": "HNSW",
                "metric_type": "COSINE",
                "params": {"M": 8, "efConstruction": 64},
            },
        )
    else:
        coll = Collection(name=name)
    # A collection must be 'loaded' into memory before it can be searched.
    coll.load()
    return coll


_state: dict = {"collection": None}


@asynccontextmanager
async def lifespan(app: FastAPI):
    connect_with_retry()
    _state["collection"] = ensure_collection()
    log.info("Search service ready.")
    yield
    connections.disconnect("default")


app = FastAPI(title="Search/RAG Service", version="1.0.0", lifespan=lifespan)


# --- Embeddings ----------------------------------------------------------------
async def embed(text: str) -> list[float]:
    """Call Ollama's embeddings endpoint and return the vector."""
    start = time.perf_counter()
    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(
            f"{settings.ollama_url}/api/embeddings",
            json={"model": settings.embed_model, "prompt": text},
        )
    EMBED_LATENCY.observe(time.perf_counter() - start)
    if resp.status_code != 200:
        raise HTTPException(status_code=502, detail=f"Embedding failed: {resp.text}")
    vector = resp.json().get("embedding")
    if not vector or len(vector) != settings.embed_dim:
        raise HTTPException(
            status_code=502,
            detail=f"Bad embedding: expected dim {settings.embed_dim}, got {len(vector) if vector else 0}",
        )
    return vector


# --- Endpoints -----------------------------------------------------------------
@app.get("/search/health")
async def health():
    ok = _state["collection"] is not None and connections.has_connection("default")
    return JSONResponse(
        status_code=200 if ok else 503,
        content={"status": "ok" if ok else "unavailable", "collection_loaded": ok},
    )


@app.get("/metrics")
def metrics():
    return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.post("/search/index")
async def index_document(req: IndexRequest):
    endpoint = "/search/index"
    start = time.perf_counter()
    try:
        vector = await embed(req.text)
        coll: Collection = _state["collection"]
        result = coll.insert([{"text": req.text, "source": req.source, "vector": vector}])
        coll.flush()  # make the new row immediately searchable
        REQUESTS.labels(endpoint, "200").inc()
        LATENCY.labels(endpoint).observe(time.perf_counter() - start)
        return {"id": int(result.primary_keys[0]), "source": req.source}
    except HTTPException:
        REQUESTS.labels(endpoint, "502").inc()
        raise
    except Exception as e:  # noqa: BLE001
        REQUESTS.labels(endpoint, "500").inc()
        log.exception("index failed")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/search/query")
async def query(req: QueryRequest):
    endpoint = "/search/query"
    start = time.perf_counter()
    top_k = req.top_k or settings.default_top_k
    try:
        vector = await embed(req.query)
        coll: Collection = _state["collection"]
        results = coll.search(
            data=[vector],
            anns_field="vector",
            param={"metric_type": "COSINE", "params": {"ef": 64}},
            limit=top_k,
            output_fields=["text", "source"],
        )
        hits = [
            {
                "id": int(hit.id),
                "score": round(float(hit.distance), 4),  # COSINE: higher = more similar
                "text": hit.entity.get("text"),
                "source": hit.entity.get("source"),
            }
            for hit in results[0]
        ]
        REQUESTS.labels(endpoint, "200").inc()
        LATENCY.labels(endpoint).observe(time.perf_counter() - start)
        return {"query": req.query, "top_k": top_k, "hits": hits}
    except HTTPException:
        REQUESTS.labels(endpoint, "502").inc()
        raise
    except Exception as e:  # noqa: BLE001
        REQUESTS.labels(endpoint, "500").inc()
        log.exception("query failed")
        raise HTTPException(status_code=500, detail=str(e))
